"""empty message

Revision ID: 19db1b56a50b
Revises: cff65cb92f6c
Create Date: 2024-02-11 23:31:40.369640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19db1b56a50b'
down_revision: Union[str, None] = 'cff65cb92f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tradesvaluebyminute', sa.Column('sell_quantity', sa.Float(), nullable=False))
    op.add_column('tradesvaluebyminute', sa.Column('buy_quantity', sa.Float(), nullable=False))
    op.drop_column('tradesvaluebyminute', 'quantity')
    op.drop_column('tradesvaluebyminute', 'market_maker')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tradesvaluebyminute', sa.Column('market_maker', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tradesvaluebyminute', sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('tradesvaluebyminute', 'buy_quantity')
    op.drop_column('tradesvaluebyminute', 'sell_quantity')
    # ### end Alembic commands ###
