"""empty message

Revision ID: 329907cfc705
Revises: 94ffa28ce571
Create Date: 2024-03-05 17:47:02.190740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329907cfc705'
down_revision: Union[str, None] = '94ffa28ce571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statvaluebymin', sa.Column('num_pf_trades', sa.Integer(), nullable=False))
    op.drop_column('statvaluebymin', 'close_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statvaluebymin', sa.Column('close_price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('statvaluebymin', 'num_pf_trades')
    # ### end Alembic commands ###
