"""empty message

Revision ID: 94ffa28ce571
Revises: e51888e23a13
Create Date: 2024-03-05 17:45:50.849518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94ffa28ce571'
down_revision: Union[str, None] = 'e51888e23a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statvaluebymin', sa.Column('close_price', sa.Integer(), nullable=False))
    op.alter_column('statvaluebymin', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statvaluebymin', 'quantity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('statvaluebymin', 'close_price')
    # ### end Alembic commands ###
