"""empty message

Revision ID: eac555869b71
Revises: eb741ae13852
Create Date: 2024-02-11 23:55:01.783908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eac555869b71'
down_revision: Union[str, None] = 'eb741ae13852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tradesvaluebyminute', sa.Column('sell_trades_count', sa.Integer(), nullable=False))
    op.add_column('tradesvaluebyminute', sa.Column('sell_average_price', sa.Float(), nullable=False))
    op.add_column('tradesvaluebyminute', sa.Column('buy_trades_count', sa.Integer(), nullable=False))
    op.add_column('tradesvaluebyminute', sa.Column('buy_average_price', sa.Float(), nullable=False))
    op.drop_column('tradesvaluebyminute', 'average_price')
    op.drop_column('tradesvaluebyminute', 'trades_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tradesvaluebyminute', sa.Column('trades_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tradesvaluebyminute', sa.Column('average_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('tradesvaluebyminute', 'buy_average_price')
    op.drop_column('tradesvaluebyminute', 'buy_trades_count')
    op.drop_column('tradesvaluebyminute', 'sell_average_price')
    op.drop_column('tradesvaluebyminute', 'sell_trades_count')
    # ### end Alembic commands ###
