"""empty message

Revision ID: eb741ae13852
Revises: 132b9714c299
Create Date: 2024-02-11 23:46:33.405012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb741ae13852'
down_revision: Union[str, None] = '132b9714c299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tradesvaluebyminute', sa.Column('trades_count', sa.Integer(), nullable=False))
    op.add_column('tradesvaluebyminute', sa.Column('average_price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tradesvaluebyminute', 'average_price')
    op.drop_column('tradesvaluebyminute', 'trades_count')
    # ### end Alembic commands ###
