"""empty message

Revision ID: eb79970bb59d
Revises: 329907cfc705
Create Date: 2024-03-05 17:59:16.590574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb79970bb59d'
down_revision: Union[str, None] = '329907cfc705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statvaluebymin', sa.Column('num_of_trades', sa.Integer(), nullable=False))
    op.drop_column('statvaluebymin', 'num_pf_trades')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statvaluebymin', sa.Column('num_pf_trades', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('statvaluebymin', 'num_of_trades')
    # ### end Alembic commands ###
