"""empty message

Revision ID: f394f550f6ea
Revises: eac555869b71
Create Date: 2024-03-05 17:03:46.717156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f394f550f6ea'
down_revision: Union[str, None] = 'eac555869b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statvaluebymin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_time', sa.DateTime(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_time')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statvaluebymin')
    # ### end Alembic commands ###
